apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mongo-container
  name: mongo-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-container
  template:
    metadata:
      labels:
        io.kompose.network/spring-sqs-ms-sqs-circuit: "true"
        io.kompose.service: mongo-container
    spec:
      containers:
        - image: mongo:latest
          name: mongo-container
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP

          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"

      restartPolicy: Always
