apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ms-received-message
  name: ms-received-message
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8081
  selector:
    io.kompose.service: ms-received-message
  type: LoadBalancer