apiVersion: v1
kind: Service
metadata:
  name: ms-send-message
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: ms-send-message
  type: LoadBalancer
