apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ms-send-message
  name: ms-send-message
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: ms-send-message
  template:
    metadata:
      labels:
        io.kompose.network/spring-sqs-ms-sqs-circuit: "true"
        io.kompose.service: ms-send-message
    spec:
      containers:
      - name: ms-send-message
        image: d4rkghost47/ms-send:v1
        ports:
        - containerPort: 8081
          hostPort: 8081
          protocol: TCP
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: sqs-microservices-configmap
              key: AWS_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: sqs-microservices-configmap
              key: AWS_SECRET_KEY
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: sqs-microservices-configmap
              key: AWS_REGION
        - name: AWS_SQS_NAME
          valueFrom:
            configMapKeyRef:
              name: sqs-microservices-configmap
              key: AWS_SQS_NAME
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      restartPolicy: Always
